markdown: kramdown
permalink: /:year/:month/:title
title: 大象植物园客厅
url: https://willwang-x.github.io/
subscribe: https://willwang-x.github.io/
exclude: [ README.md, newpost.rb ]
domain:
author: willwang
email: willwangcc@gmail.com
twitterID:
disqusShortname:
safe: true
